### PR TITLE
Allow for autosites in /htdocs subdirectories.

### PR DESCRIPTION
**Pull request by jrfnl**
This is quite a typical setup, amongst other things, used by the [ThemeReview VVV](https://github.com/aubreypwd/wordpress-themereview-vvv/).

Without this PR:
screenshot

With this PR:
screenshot

### CODE REVIEW

**Comment by jrfnl** [comment]
Just noticed #24 which looks to be a lot more comprehensive than this quick fix. Feel free to close this in favour of #24 is that would be merged.

**Comment by topdown** [comment]
I'll take a look this weekend.

**Comment by topdown** [comment]
The problem with themereview is that there is no wp-cli.yml with the package.
That file should be in the package root with the other config files with `path: htdocs` in it.
Once that is properly added everything works fine.

**Comment by topdown** [comment]
I created a PR over in ThemeReview repo https://github.com/aubreypwd/wordpress-themereview-vvv/pull/15

**Comment by jrfnl** [comment]
Thank you!

**Pull request closed without merging**
