### PR TITLE
Add mailcatcher menu item

### PR DESCRIPTION
**Pull request by atimmer**

### CODE REVIEW

**Comment by jdevalk** [comment]
Tested, works for me :)

**Comment by Mte90** [comment]
+1

**Comment by topdown** [comment]
I couldn't get this working. What are the requirements, versions, accessories, etc....?

**Comment by Mte90** [comment]
You have to use the develop branch https://github.com/Varying-Vagrant-Vagrants/VVV for use mailcatcher that now is the default branch on VVV.

**Comment by topdown** [comment]
As a note for others, I had to switch to VVV develop branch and then run `vagrant provision` to get it to update everything.

**Pull request closed without merging**
